### ISSUE TITLE
Datadog dashboard JSON

### ISSUE THREAD

**Issue by bcwilsondotcom** [mtrimarchi/MikrotikJSON4DatadogAPI#2]
Hey, thanks for creating this. I've got it running on two of my RB4011's after some troubleshooting with the date time functions.

Would you mind including the JSON for your example dashboard?

**Comment by mtrimarchi** [comment]
Hello @DevBOFH, unfortunately it's not possible to export a full dashboard in JSON format 😞

By the way I can give you this little JSON to create the "**System CPU Load**" graph i.e.:

```
{
  "viz": "timeseries",
  "requests": [
    {
      "q": "avg:system.cpu.load{$host}",
      "type": "line",
      "style": {
        "palette": "dog_classic",
        "type": "solid",
        "width": "normal"
      },
      "aggregator": "avg",
      "conditional_formats": []
    }
  ],
  "autoscale": true,
  "markers": [
    {
      "dim": "y",
      "type": "warning dashed",
      "val": 30,
      "value": "y = 30"
    },
    {
      "dim": "y",
      "min": 40,
      "max": 100,
      "value": "40 < y < 100",
      "label": "Error threshold",
      "type": "error dashed"
    }
  ],
  "yaxis": {
    "max": "100",
    "min": "0"
  }
}
```

Cheers! ✌️

**Comment by mtrimarchi** [comment]
@DevBOFH Datadog has now implemented a way to import/export full dashboard.
I'm going to share my dashboard 😉
